### ISSUE TITLE
Wiki theme, use /logos/logo.svg instead of /assets/logo.svg

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#151]
Make sure the following is adapted. 

Note that the `background-size:` takes care of the SVG at 100% for width and height on the heading.

``` css
#p-logo a {
  background: #f9f7f3 url(//www.webplatform.org/logo/logo.png);
  background: hsl(40,29%,96%) url(//www.webplatform.org/logo/logo.svg);
  background-size: 60%;
}
```
