### ISSUE TITLE
Improve site visual elements

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#165]
After a CSS experiment to review how the background pattern could be improved without use of image, let’s apply the change everywhere.

Problem is that some visual elements doesn’t play well with the new pattern.

At this time, only the [default web server page](http://173.236.254.96/) has the new pattern.

![screen shot 2015-05-07 at 16 06 48](https://cloud.githubusercontent.com/assets/296940/7524896/170a445a-f4d3-11e4-9aa4-2f6f3ac0f20c.png)

To do this, we have to remove the use of the following (and similar code);

``` css
html {
  background: #ece5d7;
  background-image: url(//www.webplatform.org/assets/bg-pattern.png);
}
```

into

``` css
html {
  background-color: #F0EBDD;
  background-image: linear-gradient(transparent 50%, rgba(219,215,202,.2) 50%);
  background-size: 3px 3px;
}
```
## Problem

The CSS badly needs some love. Making the change needs to be done everywhere, in the same time, without breaking the consistency.
- [ ] Rework [nav-bg](https://www.webplatform.org/assets/nav-bg.png) image.
- [ ] Make change
  - [ ] [blog](https://blog.webplatform.org)
  - [ ] [project](https://project.webplatform.org) until we remove it.
  - [ ] [homepage](https://www.webplatform.org)
### Blog

:-1: 

![screen shot 2015-05-07 at 15 58 10](https://cloud.githubusercontent.com/assets/296940/7525023/197a630e-f4d4-11e4-9e95-422a68854bd6.png)
### Homepage

:+1: 

![screen shot 2015-05-07 at 16 03 40](https://cloud.githubusercontent.com/assets/296940/7524822/ab1f41c8-f4d2-11e4-8aaa-873b16eaf31f.png)
## Patches
- [Homepage](https://github.com/webplatform/www.webplatform.org) w/ webplatform/www.webplatform.org@1eec7fa
